package com.softserve.hometask3part2;

public enum Breed {
    LABRADOR_RETRIEVERS, GERMAN_SHEPHERDS, GOLDEN_RETRIEVERS, FRENCH_BULLDOGS, BULLDOGS, BEAGLES, POODLES, ROTTWEILERS,
    GERMAN_SHORTHAIRED_POINTERS, YORKSHIRE_TERRIERS;
}
